spring:
  application:
    name: event-consumer
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: demo-consumer
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

demo:
  topic-name: demo-topic
