spring:
  application:
    name: event-producer
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    properties:
      # 로컬 개발 편의를 위한 idempotence 비활성화 등 추가 옵션을 여기에 정의할 수 있다.
      linger.ms: 5

demo:
  topic-name: demo-topic
  auto-publish:
    enabled: false
    interval: 5000
    message-template: "자동 발행 메시지 - %d"
